run:
  # Include test files or not.
  # Default: true
  tests: false

linters:
  disable-all: true
  enable:
    - misspell
    - govet
    - staticcheck
    - errcheck
    - unparam
    - ineffassign
    - nakedret
    - gocyclo
    - dupl
#    - goimports
    - revive
    - gosec
    - gosimple
    - typecheck
    - unused

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 600
  goimports:
    # A comma-separated list of prefixes, which, if set, checks import paths
    # with the given prefixes are grouped after 3rd-party packages.
    # Default: ""
    local-prefixes: github.com/shipengqi/golib

issues:
  exclude-rules:
    - path-except: '(xmd5\|xsha1)\.go'
      linters:
        - gosec
